import {Viewer} from './viewer.js';
const $=id=>document.getElementById(id);
let state={bodies:[],faces:[],edges:[],revision:0},token='',selected=[],tab='split',busy=false,lastPoint=null,viewer,dirty=false;
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=v=>Number(v).toLocaleString('en-US',{maximumFractionDigits:5});
const status=(message,error=false)=>{$('status').textContent=message;$('status').classList.toggle('error',error)};
const field=(label,id,value,type='number')=>`<div class="field"><label for="${id}">${label}</label><input id="${id}" type="${type}" value="${value}" ${type==='number'?'step="any"':''}></div>`;
const vec=(label,id,values=[0,0,0],pick=false)=>`<div class="field"><label>${label}</label><div class="vector">${values.map((v,i)=>`<input aria-label="${label} ${'XYZ'[i]}" id="${id}-${i}" type="number" step="any" value="${v}">`).join('')}</div>${pick?`<button class="mini" data-point="${id}">最後にクリックした点を入力</button>`:''}</div>`;
const select=(label,id,options)=>`<div class="field"><label for="${id}">${label}</label><select id="${id}">${options.map(([v,t])=>`<option value="${v}">${t}</option>`).join('')}</select></div>`;
const check=(id,label,checked=false)=>`<label class="check"><input type="checkbox" id="${id}" ${checked?'checked':''}>${label}</label>`;
const note=t=>`<div class="note">${t}</div>`;
const apply=(label='実行')=>`<button class="primary action-button" id="apply">${label}</button>`;
const v=id=>[0,1,2].map(i=>numeric(`${id}-${i}`));
function numeric(id){const input=$(id);if(!input||input.value.trim()===''||!Number.isFinite(Number(input.value)))throw Error('数値欄に有効な数値を入力してください。');return Number(input.value)}
const keys=kind=>selected.filter(id=>id.includes(':'+kind));
const bodyIds=()=>[...new Set(selected.filter(s=>s.startsWith('B')).map(s=>s.split(':')[0]))];
function changeMode(mode){viewer.mode=mode;document.querySelectorAll('[data-mode]').forEach(b=>b.classList.toggle('active',b.dataset.mode===mode))}
function selections(){viewer.selected=new Set(selected);viewer.draw();renderTree();renderConstructionTree();$('selection').innerHTML=selected.length?selected.map(id=>`<div class="selection-item"><span>${esc(id)}</span><button data-remove="${esc(id)}">×</button></div>`).join(''):'<p class="muted">未選択</p>';$('selection').querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{selected=selected.filter(x=>x!==b.dataset.remove);selections()});properties();edgeNodeInfo();perpendicularInfo()}
function pick(hit,multi){if(hit){lastPoint=hit;if(multi)selected=selected.includes(hit.id)?selected.filter(id=>id!==hit.id):[...selected,hit.id];else selected=[hit.id];status(`${hit.id} · 座標 (${hit.point.map(fmt).join(', ')}) mm${hit.exact?'':' · 表示近似点'}`)}else if(!multi)selected=[];selections()}
function renderTree(){$('body-count').textContent=state.bodies.length;$('tree').innerHTML=state.bodies.length?state.bodies.map(b=>`<div class="body-row ${bodyIds().includes(b.id)?'selected':''}"><span class="body-icon">${b.solids?'◇':'▱'}</span><button class="name" data-body="${b.id}" title="${esc(b.name)}">${esc(b.name)}</button><button class="eye" data-eye="${b.id}" title="表示を切替">${viewer.hidden.has(b.id)?'○':'●'}</button></div>`).join(''):'<div class="tree-empty">まだ形状がありません。<br>CADを開くかサンプルを追加してください。</div>';$('tree').querySelectorAll('[data-body]').forEach(b=>b.onclick=e=>{const id=b.dataset.body;if(e.ctrlKey||e.metaKey)selected=selected.includes(id)?selected.filter(x=>x!==id):[...selected,id];else selected=[id];selections()});$('tree').querySelectorAll('[data-eye]').forEach(b=>b.onclick=()=>{const id=b.dataset.eye;viewer.hidden.has(id)?viewer.hidden.delete(id):viewer.hidden.add(id);renderTree();viewer.draw()})}
function renderConstructionTree(){
  const rows=[...(state.nodes||[]).map(n=>({id:n.id,text:`${n.id} (${n.point.map(fmt).join(', ')})`,point:n.point})),...(state.lines||[]).map(l=>({id:l.id,text:`${l.id} · ${l.nodes.join(' → ')}`}))];
  $('construction-tree').innerHTML=rows.map(r=>`<div class="body-row ${selected.includes(r.id)?'selected':''}"><button class="name" data-construction="${r.id}">${esc(r.text)}</button></div>`).join('')||'<p class="muted">節点・ラインタブで作成</p>';
  $('construction-tree').querySelectorAll('[data-construction]').forEach(b=>b.onclick=e=>{const row=rows.find(r=>r.id===b.dataset.construction);if(row.point)lastPoint={id:row.id,point:row.point,exact:true};if(e.ctrlKey||e.metaKey)selected=selected.includes(row.id)?selected.filter(x=>x!==row.id):[...selected,row.id];else selected=[row.id];selections()});
}
function properties(){const id=selected.at(-1),entity=state.bodies.find(b=>b.id===id)||state.faces.find(f=>f.id===id)||state.edges.find(e=>e.id===id)||(state.nodes||[]).find(n=>n.id===id)||(state.lines||[]).find(l=>l.id===id);if(!entity){$('properties').innerHTML='<p class="muted">形状を選択すると情報が表示されます。</p>';return}const rows=[['ID',id]];if(entity.point){rows.push(['座標 [mm]',entity.point.map(fmt).join(', ')])}else if(entity.nodes){rows.push(['節点',entity.nodes.join(' → ')],['長さ',`${fmt(entity.length)} mm`])}else if(entity.solids!==undefined){rows.push(['ソリッド / 面',`${entity.solids} / ${entity.faces}`],['体積',`${fmt(entity.volume)} mm³`],['面積',`${fmt(entity.area)} mm²`],['自由 / 共有',`${entity.topology.free} / ${entity.topology.shared}`],['非多様体',entity.topology.nonmanifold],['B-rep 検査',entity.valid?'VALID':'INVALID'])}else if(entity.area!==undefined)rows.push(['曲面',entity.type],['面積',`${fmt(entity.area)} mm²`]);else rows.push(['曲線',entity.type],['長さ',`${fmt(entity.length)} mm`],['接続',entity.state]);$('properties').innerHTML=`<dl>${rows.map(([a,b])=>`<dt>${esc(a)}</dt><dd>${esc(b)}</dd>`).join('')}</dl>`}
function edgeNodeInfo(){
  if(!$('edge-node-info'))return;
  const ids=keys('E'), edge=state.edges.find(e=>e.id===ids[0]);
  if(ids.length!==1||!edge){$('edge-node-info').textContent='エッジ選択モードで、対象エッジを1本選んでください。';return}
  const reverse=!!$('edge-reverse')?.checked,a=reverse?edge.end:edge.start,b=reverse?edge.start:edge.end;
  $('edge-node-info').textContent=`${edge.id} · 長さ ${fmt(edge.length)} mm / r=0: (${a.map(fmt).join(', ')}) / r=1: (${b.map(fmt).join(', ')})${edge.closed?' / 閉曲線: n+1個のうち始点と終点は同じ座標です。':''}`;
}
function perpendicularInfo(){
  if(!$('perpendicular-info'))return;
  const nodes=selected.filter(x=>x.startsWith('N')),edges=keys('E');
  $('perpendicular-info').textContent=`節点: ${nodes.join(', ')||'未選択'} / エッジ: ${edges.join(', ')||'未選択'}`;
}
async function request(url,options={}){const response=await fetch(url,{...options,headers:{'X-GeomEditor-Token':token,...options.headers}});if(!response.ok){let err;try{err=await response.json()}catch{}throw Error(err?.error||`HTTP ${response.status}`)}return response}
async function task(fn){if(busy)return;busy=true;$('busy').hidden=false;document.body.classList.add('busy');try{await fn()}catch(e){status(e.message,true)}finally{busy=false;$('busy').hidden=true;document.body.classList.remove('busy')}}
function update(data,fit=false){state=data;selected=[];lastPoint=null;viewer.setScene(data,fit);selections();$('welcome').hidden=!!(data.bodies.length||data.nodes?.length);$('undo').disabled=!data.undo;$('redo').disabled=!data.redo;$('stats').textContent=`${data.bodies.reduce((s,b)=>s+b.solids,0)} solids · ${data.faces.length} faces · ${data.edges.length} edges · mm`;$('log').innerHTML=data.log.map(s=>`<li>${esc(s)}</li>`).join('');status(data.message);if(tab==='split')preview();if(tab==='construction')renderOperations()}
async function operation(params,fit=false){await task(async()=>{const r=await request('/api/operation',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({revision:state.revision,bodies:bodyIds(),faces:keys('F'),edges:keys('E'),...params})});update(await r.json(),fit);if(tab==='construction'&&['node_on_edge','nodes_divide_edge'].includes(params.action)){selected=[params.edge];$('edge-node-method').value=params.action;$('edge-reverse').checked=!!params.reverse;if(params.fraction!==undefined)$('edge-fraction').value=params.fraction;if(params.divisions!==undefined)$('edge-divisions').value=params.divisions;$('edge-node-method').onchange();changeMode('edge');selections()}if(params.action==='perpendicular_line'){selected=[state.lines.at(-1).id];changeMode('line');selections()}dirty=true})}
function referencePoints(){const line=(state.lines||[]).find(l=>l.id===$('reference-line')?.value);return line?.points}
function splitNormal(){const type=$('split-kind')?.value;if(type==='split_reference'){const points=referencePoints();if(!points)return null;const [a,b]=points,s=v('sweep'),t=b.map((x,i)=>x-a[i]);return[t[1]*s[2]-t[2]*s[1],t[2]*s[0]-t[0]*s[2],t[0]*s[1]-t[1]*s[0]]}if(type==='split_line'){const a=v('origin'),b=v('end'),s=v('sweep'),t=b.map((x,i)=>x-a[i]);return[t[1]*s[2]-t[2]*s[1],t[2]*s[0]-t[0]*s[2],t[0]*s[1]-t[1]*s[0]]}if(type==='split_plane')return v('normal');return null}
function preview(){try{const normal=splitNormal();viewer.setPlane($('split-kind')?.value==='split_reference'?(referencePoints()?.[0]||[0,0,0]):v('origin'),normal||[0,0,0],!!$('preview')?.checked&&!!normal)}catch{viewer.setPlane([0,0,0],[0,0,1],false)}}
function pointButtons(){document.querySelectorAll('[data-point]').forEach(b=>b.onclick=()=>{if(!lastPoint)return status('先に形状上の点をクリックしてください。端点付近でスナップできます。',true);[0,1,2].forEach(i=>$(b.dataset.point+'-'+i).value=Number(lastPoint.point[i].toPrecision(12)));status(lastPoint.exact?'クリックした点を入力しました。':'表示近似点です。厳密な位置は座標値を入力してください。');preview()})}
function bindApply(fn){$('apply').onclick=()=>{try{fn()}catch(e){status(e.message,true)}};pointButtons()}
function renderOperations(){viewer.setPlane([0,0,0],[0,0,1],false);const el=$('operations');$('step-number').textContent=String(['construction','split','solid','surface','transform','inspect'].indexOf(tab)+1).padStart(2,'0');
  if(tab==='construction'){
    const nodeOptions=(state.nodes||[]).map(n=>[n.id,n.id+' ('+n.point.map(fmt).join(', ')+')']);
    el.innerHTML='<h2>節点からラインをつくる</h2><p class="description">仮想節点は作図用の点です。2点を結んで分割工具にできます。</p>'+vec('仮想節点の座標 [mm]','node-point',[0,0,0],true)+'<button class="primary action-button" id="create-node">仮想節点を作成</button><details class="edge-node-section" open><summary>エッジ上に節点を作成</summary><button id="pick-node-edge" class="mini">エッジを選択</button><p id="edge-node-info" class="muted"></p>'+check('edge-reverse','始点と終点を反転')+select('配置方法','edge-node-method',[['node_on_edge','長さの割合で1点'],['nodes_divide_edge','n等分して n+1 点']])+field('長さの割合 r（0～1）','edge-fraction',0.1)+field('分割数 n（1～1000）','edge-divisions',10)+'<button class="primary action-button" id="create-edge-nodes">エッジ上に節点を作成</button></details><details class="edge-node-section" open><summary>節点からエッジへ垂線</summary><p class="muted">節点を選び、エッジ選択へ切り替えてCtrlでエッジを追加選択します。</p><div class="button-grid"><button id="perpendicular-pick-node">節点を選択</button><button id="perpendicular-pick-edge">エッジを追加選択</button></div><p class="muted" id="perpendicular-info"></p><button class="primary action-button" id="create-perpendicular">垂線の足とラインを作成</button><p class="muted">作成したラインは「作図ラインで分割」に使えます。3D空間の最短垂線を作り、エッジは延長しません。</p></details>'+select('始点','line-start',nodeOptions)+select('終点','line-end',nodeOptions)+'<button class="mini" id="use-selected-nodes">選択した2節点を入力</button><button class="primary action-button" id="create-line">2節点を結ぶラインを作成</button><div class="button-grid"><button id="move-node">選択節点を入力座標へ</button><button id="delete-construction">選択作図要素を削除</button></div>'+note('節点は紫の点、作図ラインは紫の線で表示。Ctrlで2節点を選べます。ライン作成後は「分割・評価ライン」→「作図ラインで分割」を使用します。節点を動かしても、すでに分割したCAD形状は変わりません。');
    if(nodeOptions.length>1)$('line-end').value=nodeOptions[1][0];
    changeMode('node');pointButtons();
    const guard=fn=>()=>{try{fn()}catch(e){status(e.message,true)}};
    $('perpendicular-pick-node').onclick=()=>changeMode('node');
    $('perpendicular-pick-edge').onclick=()=>changeMode('edge');
    perpendicularInfo();
    $('create-perpendicular').onclick=guard(()=>{const nodes=selected.filter(x=>x.startsWith('N')),edges=keys('E');if(nodes.length!==1||edges.length!==1)throw Error('節点1つとエッジ1本をCtrlで選択してください。');operation({action:'perpendicular_line',node:nodes[0],edge:edges[0]})});
    $('pick-node-edge').onclick=()=>changeMode('edge');
    $('edge-reverse').onchange=edgeNodeInfo;
    const methodFields=()=>{$('edge-fraction').closest('.field').hidden=$('edge-node-method').value!=='node_on_edge';$('edge-divisions').closest('.field').hidden=$('edge-node-method').value!=='nodes_divide_edge'};
    $('edge-node-method').onchange=methodFields;methodFields();edgeNodeInfo();
    $('create-edge-nodes').onclick=guard(()=>{const edges=keys('E');if(edges.length!==1)throw Error('対象エッジを1本選んでください。');const action=$('edge-node-method').value;operation({action,edge:edges[0],reverse:$('edge-reverse').checked,...(action==='node_on_edge'?{fraction:numeric('edge-fraction')}:{divisions:numeric('edge-divisions')})})});
    $('create-node').onclick=guard(()=>operation({action:'node_create',point:v('node-point')},!state.bodies.length));
    $('use-selected-nodes').onclick=guard(()=>{const ids=selected.filter(x=>x.startsWith('N'));if(ids.length!==2)throw Error('異なる2節点をCtrlで選択してください。');$('line-start').value=ids[0];$('line-end').value=ids[1]});
    $('create-line').onclick=()=>operation({action:'line_create',nodes:[$('line-start').value,$('line-end').value]});
    $('move-node').onclick=guard(()=>{const nodes=selected.filter(x=>x.startsWith('N'));if(nodes.length!==1)throw Error('移動する節点を1つ選択してください。');operation({action:'node_move',node:nodes[0],point:v('node-point')})});
    $('delete-construction').onclick=()=>operation({action:'construction_delete',construction:selected.filter(x=>/^[NL]/.test(x))});
  }else if(tab==='split'){
    el.innerHTML='<h2>境界をつくる</h2><p class="description">評価ライン・水位面を、実際のCAD分割境界として追加します。</p>'+select('分割方法','split-kind',[['split_plane','平面で分割 / 水位面'],['split_line','2点の線を投影して分割'],['split_reference','作図ラインで分割'],['split_revolve','ラインの回転面で分割'],['perpendicular','直線エッジに垂直'],['parallel','直線エッジに平行'],['split_tool','選択面を工具に分割']])+select('対象','scope',[['solid','ボディ全体を分割'],['surface','選択面だけを分割（評価ライン）']])+'<div id="split-fields"></div>'+field('演算許容差 [mm]','tolerance','0.000001')+check('preview','分割平面をプレビュー',true)+apply('分割を実行')+note('水面に合わせる場合: Z法線 (0, 0, 1)、原点Zに水位を指定。後段でも境界を保持するメッシュ設定が必要です。');
    const fields=()=>{const kind=$('split-kind').value;let html='';if(kind==='split_reference')html=select('作図ライン','reference-line',(state.lines||[]).map(l=>[l.id,`${l.id}: ${l.nodes.join(' → ')}`]))+vec('投影方向','sweep',[0,1,0])+check('extend','ラインを両方向へ延長して分割',true)+note('工具ラインを選び、分割するボディまたは面をクリックしてください。作図ライン自体はCAD出力に含みません。');else if(kind==='split_revolve')html=select('回転するライン / CADエッジ','revolve-source',[...(state.lines||[]).map(l=>[l.id,`${l.id}: ${l.nodes.join(' → ')}`]),...state.edges.map(e=>[e.id,`${e.id}: ${e.type}`])])+select('回転軸の指定','revolve-axis-mode',[['vector','軸上の点と方向'],['nodes','2つの仮想節点']])+'<div id="revolve-vector">'+vec('軸上の点 [mm]','axis-origin',[0,0,0])+vec('軸方向（右ねじの正方向）','axis-direction',[0,0,1])+'</div><div id="revolve-nodes" hidden>'+select('軸の始点','axis-node-a',(state.nodes||[]).map(n=>[n.id,n.id]))+select('軸の終点','axis-node-b',(state.nodes||[]).map(n=>[n.id,n.id]))+'<button id="revolve-use-nodes">Ctrl選択した2節点を入力</button></div>'+field('開始角度 [deg]','revolve-start',0)+field('回転角度 [deg]（負で逆回転）','revolve-angle',360)+note('ラインの有限長を回転した面で分割します。軸は始点→終点の方向です。工具が対象を横切るように指定してください。回転面のプレビューは未対応です。');else if(kind==='split_tool')html=note('対象ボディ→工具フェイスの順に Ctrl 選択してください。工具面は有限のまま使用します。');else{html=vec('基準点 / 始点 [mm]','origin',[0,0,30],true);if(kind==='split_plane')html+=select('主軸平面','axis-preset',[['z','Z = 一定（水平面）'],['x','X = 一定'],['y','Y = 一定'],['custom','任意法線']])+vec('平面の法線','normal',[0,0,1]);if(kind==='split_line')html+=vec('終点 [mm]','end',[60,0,30],true)+vec('投影方向','sweep',[0,1,0])+check('extend','線を両方向へ延長して分割',true);if(kind==='parallel')html+=vec('投影方向','sweep',[0,0,1]);if(['parallel','perpendicular'].includes(kind))html+=note('基準となる直線エッジを1本選択。面だけを分割するときは対象面も Ctrl 選択。')}$('split-fields').innerHTML=html;if($('reference-line')){const id=selected.find(x=>x.startsWith('L'));if(id)$('reference-line').value=id}pointButtons();if($('revolve-axis-mode')){$('revolve-axis-mode').onchange=()=>{const nodes=$('revolve-axis-mode').value==='nodes';$('revolve-vector').hidden=nodes;$('revolve-nodes').hidden=!nodes;if(nodes)changeMode('node')};$('revolve-use-nodes').onclick=()=>{const ids=selected.filter(id=>id.startsWith('N'));if(ids.length!==2)return status('軸の始点、終点の順に2節点をCtrl選択してください。',true);$('axis-node-a').value=ids[0];$('axis-node-b').value=ids[1];changeMode($('scope').value==='surface'?'face':'body')};const source=selected.find(id=>id.startsWith('L')||id.includes(':E'));if(source)$('revolve-source').value=source}if($('axis-preset'))$('axis-preset').onchange=()=>{const index={x:0,y:1,z:2}[$('axis-preset').value];if(index!==undefined)[0,1,2].forEach(i=>$('normal-'+i).value=i===index?1:0);preview()};el.querySelectorAll('input').forEach(i=>i.addEventListener('input',preview));if($('reference-line'))$('reference-line').onchange=preview;preview()};$('split-kind').onchange=fields;$('scope').onchange=()=>changeMode($('scope').value==='surface'?'face':'body');fields();changeMode('body');
    bindApply(()=>{const action=$('split-kind').value,p={action,scope:$('scope').value,tolerance:numeric('tolerance')};if(action==='split_reference'){p.line=$('reference-line').value;p.sweep=v('sweep');p.extend=$('extend').checked;if(!p.line)throw Error('先に2節点から作図ラインを作成してください。')}else if(action==='split_revolve'){p.source=$('revolve-source').value;p.axis_mode=$('revolve-axis-mode').value;p.angle=numeric('revolve-angle');p.start_angle=numeric('revolve-start');if(p.axis_mode==='nodes')p.axis_nodes=[$('axis-node-a').value,$('axis-node-b').value];else{p.axis_origin=v('axis-origin');p.axis_direction=v('axis-direction')}}else if(action==='split_tool'){p.tool=keys('F').at(-1);if(!p.tool)throw Error('工具面を選んでください。');p.faces=keys('F').filter(x=>x!==p.tool);p.bodies=bodyIds().filter(id=>id!==p.tool.split(':')[0]);if(!p.bodies.length)throw Error('工具面とは別の対象ボディを選んでください。')}else{p.origin=v('origin');if(action==='split_plane')p.normal=v('normal');if(action==='split_line'){p.end=v('end');p.sweep=v('sweep');p.extend=$('extend').checked}if(['parallel','perpendicular'].includes(action)){p.edge=keys('E')[0];if(action==='parallel')p.sweep=v('sweep')}}operation(p)});
  }else if(tab==='solid'){
    el.innerHTML='<h2>ソリッドを編集</h2><p class="description">ブーリアンは選択順の先頭が対象、以降が工具です。</p>'+select('操作','solid-kind',[['partition','共有境界付き結合'],['union','和集合 / Fuse'],['difference','差集合 / Cut'],['intersection','共通部分 / Common'],['explode','ソリッドごとに分離'],['fillet','エッジにフィレット'],['chamfer','エッジに面取り'],['defeature','選択面を除去・形状修復'],['delete','選択ボディを削除']])+'<div id="solid-fields"></div>'+apply()+note('共有境界付き結合は内部境界を残します。和集合は内部の体積境界を除去します。');
    const fields=()=>{const kind=$('solid-kind').value;$('solid-fields').innerHTML=['fillet','chamfer'].includes(kind)?field(kind==='fillet'?'半径 [mm]':'面取り寸法 [mm]','size',2):['partition','union','difference','intersection'].includes(kind)?check('keep-tools','工具ボディを残す'):kind==='defeature'?note('穴・フィレットなどを構成する面を選択します。周囲の面で閉じられる場合だけ成功します。'):'';changeMode(['fillet','chamfer'].includes(kind)?'edge':kind==='defeature'?'face':'body')};$('solid-kind').onchange=fields;fields();bindApply(()=>{const action=$('solid-kind').value;if(action==='delete'&&!confirm('選択ボディを削除します。元に戻す操作で復元できます。'))return;operation({action,...($('size')?{size:numeric('size')}:{}),keep_tools:!!$('keep-tools')?.checked})});
  }else if(tab==='surface'){
    el.innerHTML='<h2>サーフェイスを編集</h2><p class="description">面の抽出・作成と接続を整えます。</p>'+select('操作','surface-kind',[['extract','選択面を抽出 / 複製'],['offset','選択面のオフセットを作成'],['extrude','選択した平面を押出し'],['patch','閉じた平面ループから面を作成'],['sew','サーフェイスを縫合'],['unify','同一面の分割を解除']])+'<div id="surface-fields"></div>'+apply();
    const fields=()=>{const kind=$('surface-kind').value;let html='';if(kind==='offset')html=field('法線方向の距離 [mm]','distance',2)+note('独立したオフセット面を追加します。元のソリッド表面を置換する操作ではありません。');if(kind==='extrude')html=vec('押出しベクトル [mm]','delta',[0,0,10]);if(kind==='sew')html=field('接続許容差 [mm]','tolerance',0.000001)+check('make-solid','閉じたシェルをソリッド化')+note('独立サーフェイス・シェルのボディを選択してください。');if(kind==='unify')html=note('同じ基礎曲面上の面を結合します。必要な評価ラインも消える場合があります。');if(kind==='patch')html=note('1つの閉じた平面ループのエッジを選択。パッチ作成後に縫合してください。');$('surface-fields').innerHTML=html;changeMode(kind==='patch'?'edge':['sew','unify'].includes(kind)?'body':'face')};$('surface-kind').onchange=fields;fields();bindApply(()=>operation({action:$('surface-kind').value,...($('distance')?{distance:numeric('distance')}:{}),...($('delta-0')?{delta:v('delta')}:{}),...($('tolerance')?{tolerance:numeric('tolerance')}:{}),make_solid:!!$('make-solid')?.checked}));
  }else if(tab==='transform'){
    el.innerHTML='<h2>配置を整える</h2><p class="description">選択ボディを移動・回転・複製します。内部単位は mm です。</p>'+select('操作','transform-kind',[['translate','平行移動'],['rotate','軸まわりに回転'],['scale','原点基準で拡大縮小'],['mirror','平面で鏡映']])+'<div id="transform-fields"></div>'+check('copy','元の形状を残して複製')+apply();
    const fields=()=>{const kind=$('transform-kind').value;let html='';if(kind==='translate')html=vec('移動量 [mm]','delta',[10,0,0]);if(kind==='rotate')html=vec('軸の基準点 [mm]','origin')+vec('回転軸','axis',[0,0,1])+field('回転角度 [deg]','angle',90);if(kind==='scale')html=field('倍率（原点基準）','factor',1)+note('座標値を実際に拡大・縮小します。単なる単位表示の変更ではありません。');if(kind==='mirror')html=vec('鏡映面の基準点 [mm]','origin')+vec('鏡映面の法線','normal',[1,0,0]);$('transform-fields').innerHTML=html};$('transform-kind').onchange=fields;fields();changeMode('body');bindApply(()=>{const action=$('transform-kind').value,p={action,copy:$('copy').checked};for(const id of ['delta','origin','axis','normal'])if($(id+'-0'))p[id]=v(id);for(const id of ['angle','factor'])if($(id))p[id]=numeric(id);operation(p)});
  }else{
    el.innerHTML='<h2>形状を確かめる</h2><p class="description">体積・面積・接続と、形状の整合性を確認します。</p>'+field('修復許容差 [mm]','tolerance',0.000001)+'<div class="button-grid"><button id="validate">全ボディを検査</button><button id="measure">最短距離を測定</button><button id="heal">選択ボディを修復</button><button id="rename">名前を変更</button></div><div id="inspection-result"></div>'+note('自由エッジがあるサーフェイスは正常な場合があります。分割した複数ソリッドの共有面周りでは、非多様体エッジが生じる場合があります。');
    $('validate').onclick=()=>{const lines=state.bodies.map(b=>`${b.id}: ${b.valid?'VALID':'INVALID'} / 自由 ${b.topology.free} / 共有 ${b.topology.shared} / 非多様体 ${b.topology.nonmanifold}`);$('inspection-result').innerHTML=note(lines.map(esc).join('<br>')||'形状がありません。');status('全ボディのB-rep検査結果を表示しました。')};$('measure').onclick=()=>task(async()=>{const r=await request('/api/measure',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({entities:selected})}),m=await r.json();$('inspection-result').innerHTML=note(`最短距離: ${fmt(m.distance)} mm`);status(`最短距離 ${fmt(m.distance)} mm`)});$('heal').onclick=()=>{try{operation({action:'heal',tolerance:numeric('tolerance')})}catch(e){status(e.message,true)}};$('rename').onclick=()=>{const b=state.bodies.find(b=>b.id===bodyIds()[0]);if(!b)return status('ボディを選んでください。',true);const name=prompt('ボディ名',b.name);if(name)operation({action:'rename',name})};
  }
}
async function importFile(file,project=false){if(!file)return;if(project&&dirty&&!confirm('現在のモデルを置き換えます。未保存の変更があります。続けますか？'))return;await task(async()=>{const r=await request(project?'/api/project':`/api/import?name=${encodeURIComponent(file.name)}`,{method:'POST',headers:{'Content-Type':'application/octet-stream'},body:file});update(await r.json(),true);dirty=!project})}
async function download(url,filename,isProject=false){await task(async()=>{const r=await request(url),blob=await r.blob(),link=document.createElement('a'),objectURL=URL.createObjectURL(blob);link.href=objectURL;link.download=filename;link.click();setTimeout(()=>URL.revokeObjectURL(objectURL),1000);if(isProject)dirty=false;status(`${filename} をダウンロードしました。${/\.(step|iges)$/.test(filename)&&state.bodies.reduce((s,b)=>s+b.solids,0)>1?' 領域間の共有接続は受け側で再構築してください。':''}`)})}
async function init(){try{viewer=new Viewer($('canvas'),pick);token=(await(await request('/api/session')).json()).token;update(await(await request('/api/state')).json(),true);renderOperations();$('open').onclick=$('welcome-open').onclick=()=>$('cad-file').click();$('load-project').onclick=()=>$('project-file').click();$('cad-file').onchange=e=>{importFile(e.target.files[0]);e.target.value=''};$('project-file').onchange=e=>{importFile(e.target.files[0],true);e.target.value=''};$('export').onclick=()=>{const fmt=$('export-format').value;download(`/api/export?format=${fmt}`,`geometry.${fmt}`)};$('save-project').onclick=()=>download('/api/project','geometry.geomproj',true);$('add-sample').onclick=()=>operation({action:'sample',name:$('sample').value},true);$('welcome-sample').onclick=()=>operation({action:'sample',name:'tank'},true);$('undo').onclick=()=>operation({action:'undo'});$('redo').onclick=()=>operation({action:'redo'});$('clear-selection').onclick=()=>{selected=[];selections()};$('fit').onclick=()=>viewer.fit();$('wire').onclick=()=>{viewer.wireOnly=!viewer.wireOnly;$('wire').classList.toggle('active',viewer.wireOnly);viewer.draw()};$('topology').onclick=()=>{viewer.topology=!viewer.topology;$('topology').classList.toggle('active',viewer.topology);viewer.draw()};$('toggle-log').onclick=()=>$('log').hidden=!$('log').hidden;document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>changeMode(b.dataset.mode));document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>viewer.view(b.dataset.view));document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{tab=b.dataset.tab;document.querySelectorAll('[data-tab]').forEach(x=>x.classList.toggle('active',x===b));renderOperations()});
    const drop=document.querySelector('.viewport');drop.addEventListener('dragover',e=>{e.preventDefault();drop.classList.add('drop-target')});drop.addEventListener('dragleave',()=>drop.classList.remove('drop-target'));drop.addEventListener('drop',e=>{e.preventDefault();drop.classList.remove('drop-target');const file=e.dataTransfer.files[0];if(file)importFile(file,file.name.endsWith('.geomproj'))});document.addEventListener('keydown',e=>{if(['INPUT','TEXTAREA','SELECT'].includes(document.activeElement.tagName))return;if(e.key==='Escape'){selected=[];selections()}if(e.key.toLowerCase()==='f')viewer.fit();if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){e.preventDefault();operation({action:e.shiftKey?'redo':'undo'})}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='y'){e.preventDefault();operation({action:'redo'})}});window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue=''}});
  }catch(e){status(`起動エラー: ${e.message}`,true)}}
init();
